name: deep_sleep
description: Application that helps to meditate and sleep
version: 1.3.0+5

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  assets_audio_player: ^3.0.3+6
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  fl_chart: ^0.40.0
  flowder: ^0.2.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.7
  flutter_svg: ^1.0.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  hive_flutter: ^1.1.0
  jiffy: ^5.0.0
  marquee: ^2.2.0
  page_transition: ^2.0.2
  palette_generator: ^0.3.2
  path_provider: ^2.0.7
  url_launcher: ^6.0.12
  webview_flutter: ^3.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "res/icon.png"

flutter_native_splash:
  background_image: res/splash.png

flutter:
  uses-material-design: true
  assets:
    - asset/

dev_dependencies: 
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.3
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1
  lint: ^1.8.1
